### ISSUE TITLE
SyntaxError: Unexpected identifier in module import

### ISSUE THREAD

**Issue by davidkhala** [5sWind/nodejs-crypto-lab#1]
```
davidliu@davidliu-hyperledger:~/Documents/nodejs-crypto-lab$ node interative_mode.js 'abc'
/home/davidliu/Documents/nodejs-crypto-lab/interative_mode.js:1
import secureKeyGen from "./utils/secp256r1_gen";
       ^^^^^^^^^^^^

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:703:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:824:10)
    at internal/main/run_main_module.js:17:11
```

nodejs version v12.1.0

**Comment by ghpZ54K8ZRwU62zGVSePPs97yAv9swuAY0mVDR4** [comment]
Hi @davidkhala, I just updated a new version. You can see in the README.
Welcome feedback!

My node version: v8.12.0.

**Comment by davidkhala** [comment]
what I see in newer version: 
```
$ node --experimental-modules interative_mode.mjs abc
(node:16500) ExperimentalWarning: The ESM module loader is experimental.
==== Generating keypairs. ====
Segmentation fault (core dumped)
```
Segmentation fault?

**Comment by ghpZ54K8ZRwU62zGVSePPs97yAv9swuAY0mVDR4** [comment]
@davidkhala on my console the records are:

```
$ node --experimental-modules interative_mode.mjs "my cats"
(node:5626) ExperimentalWarning: The ESM module loader is experimental.
==== Generating keypairs. ====
Generated Private Key:  { privateKey: 'UkVDMgAAAC2+2PEAAL/c1VzKIw8ZzMs+F86gQNf77Pjz2AeMJYjIwRuW7qkJ' }
Generated Public Key:  { publicKey: 'VUVDMgAAAC3reMUXA7cQYALGorHz0G+aSBR/DzEerGzhWVP6DeYNvjSejpkG' }
```

it works for me then...
While `segmentation fault` is caused by a program trying to read or write an illegal memory location...
This issue may caused by the Themis library. Themis is written by C++, it does read or write memory on machine using the pointer I thought.

**Comment by davidkhala** [comment]
Which OS, node version is on your side?

**Comment by ghpZ54K8ZRwU62zGVSePPs97yAv9swuAY0mVDR4** [comment]
@davidkhala I would recommend you to install Themis Core following the [Quick Start](https://github.com/cossacklabs/themis/wiki/NodeJS-howto#quickstart), and rerun it again.
Welcome feedback.

**Comment by davidkhala** [comment]
actually I have followed the guideline to install themis core (my OS is Ubuntu 18). I guess there is compatibility problem on themis so I think simulating your environment is more easy to me.

**Comment by ghpZ54K8ZRwU62zGVSePPs97yAv9swuAY0mVDR4** [comment]
My OS is macOS Mojave 10.14.4 and my node version is v8.12.0.

**Comment by davidkhala** [comment]
> My OS is macOS Mojave 10.14.4 and my node version is v8.12.0.

tested done on this environment setting(almost, please see in  #2 )
